// <auto-generated />
namespace RaceDay.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RaceDayMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RaceDayMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201712070434387_RaceDayMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
